language: ruby

gemfile:
  - Gemfile

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0

script: bundle exec rake test

notifications:
  email: false
  irc:
    channels:
      - "irc.codehaus.org#livetribe"
    template:
      - "[#%{build_number}] %{message} %{build_url}"
      - "[#%{build_number}] %{commit} on %{branch} by %{author}"
      - "[#%{build_number}] %{compare_url}"
    on_success: always
    on_failure: always
    use_notice: false

env:
  global:
    - secure: H7/JXdFS43qDOfOOR9/5skyfi/BsxrWIH0qivgxdYw7mDXdIsd4rwx+K23IbHqaZdTiCT9ZSJMtMLZLGyw/t1MnZcNw6oMeXDXPZDNeSP7NtceO+M0lA3O03gSF/fw4Kl87wdfuutelR7E+4JodW6tfT38sJON8TW8M2izKxoI0=
    - secure: cUoopI5atAtVJQMm7HgnVR60azUzGv3JITAPbQGAG3Q/uS1JNpmJIClqInqPv5pz9apvMoVEQa6mWaC6Gm4e2BHlUNjmGJumUU11Ke1LBl3rCGeSCKZpO/JTncMvDJnnkM/gHmFOroS9frgibJreGturWFPXdt30wP1Yjd6cR9E=
