language: ruby

gemfile:
  - Gemfile

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0

script: bundle exec rake test

notifications:
  email: false
  irc:
    channels:
      - "irc.codehaus.org#livetribe"
    template:
      - "[#%{build_number}] %{message} %{build_url}"
      - "[#%{build_number}] %{commit} on %{branch} by %{author}"
      - "[#%{build_number}] %{compare_url}"
    on_success: always
    on_failure: always
    use_notice: false

env:
  global:
    - secure: "iLCQwTk9l92Vc4hFY5e1OmHshxu22COOKKobj/qjFvZ+3ZWDo0nyJwumvRaYE5z94TSMZAgSLKHks3yqp01Vwo+UxWQm++l9CUacjtRgLi3gBe8VASY7lCKY2hmRl2GB5TuYC9OwCag8Ak167Z7ZMeCtIzH18qD0nTS72jdybGQ="
    - secure: "gWxwV1r7pashZIcLJBDgPU8l8V2/EcX8q6j6Y6KXwd2L/2KkBXsCXoVr7S3TSx03Yy0Pu6pinm16qAMysCsv/GoHJckKFaO5Zhxp6Pgl1d3rkA1U2t8TymRqY1NYukju5gpMS9TP3EM1mbownwnMas5V5DGSLSrWDVfqxR1fQVc="
