sudo: false

language: ruby

gemfile:
  - Gemfile

rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1

script: bundle exec rake test

notifications:
  slack:
    secure: C8LEbbnwJuGA2+/tjDRYhwkKi+7HCfixljLiRNPgMkqXDldmEtqcjhHIHcNH7SJTE5Xgysw6HIhj9Z8grDKYAlirERvDDeVqlb3HDGO+AKCRDveIVqmMDADFQCnZY+rWP/skrTrE5+xA7ERGNEPMup4IlMpQB1jdLF7hFU6BpmCuCkYzwLXqrXqb7LVVzwxf+6GhdTRNq4Ot78eyk2UqtFdohdwmzVeHF/KwrLT96BDYFuBT/AAwZrxAltD4QjP2N+PxzP4WW6sZZ5LSNLZAurHzA8NEpqOy7Uv5tX5WLpSKbMAMcOp8l0XUfejo2vQNJ5l5l8cH0fiFr9qx4soIVWLdYfkCeBtp8JzC05Xjz5/Rx42Nu+v8eKUCtJfbyGxeSB3vu8PYQ9z6yJYCSO4CnSKzkuoYG4FCXZ39zm3oFm0K2z6e1A2SWr4OU72Ez8YYAAcs3Y+Ml5mUWC+tt0jyhrUwJmIkRkBj8B1RYG4Oeq/TlJtIzbEikxwR/pu7h7BQlGeIFHKWjSTxpcXa1BqePMiSMIzPoFRXwuXij6o3H1/ShXuxfMG4FMMcqkzY8BvLpE4s9Y8c2rW/Stee59HODNOgOlDIdxfvSYiRAgLS7iN4x9gYZhfM+zl4MO7EGWSGDzIcyiUeUF8yj57vVr1RR+M+5mBiogKkgW2h9RVz2qc=

env:
  global:
    - secure: H7/JXdFS43qDOfOOR9/5skyfi/BsxrWIH0qivgxdYw7mDXdIsd4rwx+K23IbHqaZdTiCT9ZSJMtMLZLGyw/t1MnZcNw6oMeXDXPZDNeSP7NtceO+M0lA3O03gSF/fw4Kl87wdfuutelR7E+4JodW6tfT38sJON8TW8M2izKxoI0=
    - secure: cUoopI5atAtVJQMm7HgnVR60azUzGv3JITAPbQGAG3Q/uS1JNpmJIClqInqPv5pz9apvMoVEQa6mWaC6Gm4e2BHlUNjmGJumUU11Ke1LBl3rCGeSCKZpO/JTncMvDJnnkM/gHmFOroS9frgibJreGturWFPXdt30wP1Yjd6cR9E=
