language: ruby

gemfile:
  - Gemfile

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0

script: bundle exec rake test

notifications:
  email: false
  irc:
    channels:
      - "irc.codehaus.org#livetribe"
    template:
      - "[#%{build_number}] %{message} %{build_url}"
      - "[#%{build_number}] %{commit} on %{branch} by %{author}"
      - "[#%{build_number}] %{compare_url}"
    on_success: always
    on_failure: always
    use_notice: false

env:
  global:
    - secure: UXXJjQkAdGlJ+2YauP2/JmCfwA3tokSLTXnpJVu7KwgNK4TlLIEK0tvoipYg8LVknyIRUr1MlEXs8C+Eqh2BabXY6Gg4f61ZJBrhtou9onrZwEPygqKH7w5abexCRI4JXPm7LcFzgslPmBXE2zybMpnL3jsKL01Uh7Visvrlzzs=
    - secure: ns4ZiGt2CtKUJHAGdbGtTBdAbQHOZV2VKtiwRP9k+VA6iB12vKy+D55SuC68a5bgk7lWutvJoUmwMGS1UV9hgVK9TU3TGBXccxCJEK1U8SguIsKM6+YeBnGujGpi+9XrdE0JShL79xzo0JPluKq/3H/6zSEtq3dIP7CJO6nBnPM=
