sudo: false

language: ruby

gemfile:
  - Gemfile

rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0

script: bundle exec rake test

notifications:
  slack:
    secure: l92+ObfDs7Nft+F+8cEzUwqUS0KS20217P+2mC0ZAsGnLBmVRyN1LBCxJRmiXXpUFxSALGDhMloAEwgOPFPdPQ5N5LdPjCdZWo0BnM2gvD4j7aM4aJeUh3IxWtrjHeZtRLm1Uy63NhMlByEjKXToykEaERyx4GIllreQGXwFcuw=

env:
  global:
    - secure: H7/JXdFS43qDOfOOR9/5skyfi/BsxrWIH0qivgxdYw7mDXdIsd4rwx+K23IbHqaZdTiCT9ZSJMtMLZLGyw/t1MnZcNw6oMeXDXPZDNeSP7NtceO+M0lA3O03gSF/fw4Kl87wdfuutelR7E+4JodW6tfT38sJON8TW8M2izKxoI0=
    - secure: cUoopI5atAtVJQMm7HgnVR60azUzGv3JITAPbQGAG3Q/uS1JNpmJIClqInqPv5pz9apvMoVEQa6mWaC6Gm4e2BHlUNjmGJumUU11Ke1LBl3rCGeSCKZpO/JTncMvDJnnkM/gHmFOroS9frgibJreGturWFPXdt30wP1Yjd6cR9E=
